# Generated by Django 5.2.3 on 2025-06-17 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_name', models.CharField(max_length=50, unique=True)),
                ('tx_location', models.CharField(max_length=50)),
                ('tx_status', models.CharField(choices=[('O', 'Operational'), ('S', 'Stopped'), ('M', 'Maintenance')], default='O', max_length=1)),
            ],
        ),
    ]
